---
name: "DocBook/AsciiDoc building"
description: "Build DocBook/AsciiDoc documents with DAPS"
author: "@sknorr"
inputs:

  dc-files:
    description: "DC files to build."
    required: true

  format-html:
    description: "Whether to build HTML documents."
    required: false
    default: true

  format-single-html:
    description: "Whether to build single-HTML documents."
    required: false
    default: true

  format-pdf:
    description: "Whether to build PDF documents."
    required: false
    default: false

  xml-schema:
    description: "Schema file to use for validation ('geekodoc1', 'geekodoc2', 'docbook51', 'docbook52'). DC file options take precedence over this setting."
    required: false
    default: "geekodoc2"


outputs:
  exit-build:
    description: "Overall exit code for all included builds. 0 = all builds successful, <0 = at least one build failed."
  artifact-name:
    description: "Naming suggestion for artifact upload (`build-` + SHA-1 sum of input `dc-files` string)."
  artifact-dir:
    description: "Local path to generated output documents."

runs:
   using: docker
   image: "Dockerfile"
   args:
    - dc-files=${{ inputs.dc-files }}
    - format-html=${{ inputs.format-html }}
    - format-single-html=${{ inputs.format-single-html }}
    - format-pdf=${{ inputs.format-pdf }}
    - xml-schema=${{ inputs.xml-schema }}
