---
name: "DocBook/AsciiDoc validation"
description: "Validate DocBook/AsciiDoc documents with DAPS"
author: "@tomschr/@sknorr"
inputs:

  mode:
    description: "Whether to check DC file soundness ('soundness'), select DC files for validation ('list-validate'), or select DC files for building ('list-build')."
    required: true
  merge-runs:
    description: "Only with 'use-case=list-*': If there are more than 8 build/validate runs, run multiple runs in same runner to avoid incurring a container image download each time."
    required: false
    default: 'true'
  original-org:
    description: "For 'use-case=list-build': The GitHub org name of the original repo. Builds can usually only be uploaded from within the original repo, not forks. This parameter will disable builds for forked repos."
    required: false
    default: ''
  ignore-files:
    description: "An array of DC files to ignore. You can use literal values or glob patterns"
    required: false
    default: ''

outputs:
  dc-list:
    description: "For 'use-case=list-...': A list of DC files as JSON."
  allow-build:
    description: "For 'use-case=list-build': Builds are only allowed if susedoc.github.io configuration is correct."
  relevant-branches:
    description: "For 'use-case=list-build': Branches from the source repo that are still relevant and must not be cleaned up during publishing."

runs:
   using: docker
   image: "Dockerfile"
   args:
    - mode=${{ inputs.mode }}
    - merge-runs=${{ inputs.merge-runs }}
    - original-org=${{ inputs.original-org }}
    - ignore-files=${{ inputs.ignore-files }}
