---
name: "DocBook/AsciiDoc validation"
description: "Validate DocBook/AsciiDoc documents with DAPS"
author: "@tomschr/@sknorr"
inputs:

  dc-files:
    description: "DC files to validate, space-separated (`DC-a DC-b`)."
    required: true

  validate-ids:
    description: "Enable check whether referenced xml:ids adhere to the character set `[a-z0-9-]` (`daps validate --validate-ids`)."
    required: false
    default: true

  validate-images:
    description: "Enable check whether all referenced images exist (daps validate --validate-images)"
    required: false
    default: true

  validate-tables:
    description: "Enable check whether all tables within the document are valid (`daps/libexec/validate-tables.py`)."
    required: false
    default: true

  xml-schema:
    description: "XML schema to use for validation ('geekodoc1', 'geekodoc2', 'docbook51'). DC file options take precedence over this setting."
    required: false
    default: "geekodoc1"

outputs:
  exit-validate:
    description: "Overall exit code for all included validates. 0 = all validates successful, < 0 = at least one validate failed."


runs:
   using: docker
   image: "Dockerfile"
   args:
    - dc-files=${{ inputs.dc-files }}
    - validate-ids=${{ inputs.validate-ids }}
    - validate-images=${{ inputs.validate-images }}
    - validate-tables=${{ inputs.validate-tables }}
    - xml-schema=${{ inputs.xml-schema }}
