= Continuous Documentation for SUSE Documentation

This repository contains tooling to quickly set up Travis CI on SUSE and openSUSE documentation repositories.

Currently, setting up this repository means that the following checks will be run automatically:

* XML validation with DAPS (using link:https://github.com/openSUSE/geekodoc[Geekodoc] for DocBook 5 content)

* Check for IDs that contain dots and underscores

* Check for missing images

Additionally, you can use Travis CI to push live builds to susedoc.github.io.
For details, see https://github.com/openSUSE/doc-ci#travis-draft-builds.


== Enabling Travis for Doc Repositories

To enable Travis in doc repo, follow the steps below:


=== Activating Travis Web UI

Before you can use Travis, you need to activate the respective repository on our SUSE page:

. Open https://travis-ci.org/profile/SUSE and search for your repository.
If you cannot find it, click the "Sync account" button on the upper right corner.

. Enable the doc repo in Travis.


=== Configuring the GitHub Web UI

Enable the Travis service in GitHub as follows:

. Open your repo's "Settings" page.

. Under "Webhooks", choose "Add webhook".

. Use the following settings:
.. Payload URL: `https://notify.travis-ci.org`
.. Content Type: `application/x-www-form-urlencoded` (default)
.. [x] Enable SSL
.. [x] Send individual events:
... Branch or tag creation
... Pull requests
... Pushes
.. [x] Active

. Click "Add webhook".


=== Configuring the Documentation Repository

Use the following final steps:

. In your doc repo, create a feature branch (for example, `feature/travis`):
+
----
git checkout -b feature/travis
----

. Copy the following files from this repo into your doc repo:
.. `travis/template/.travis.yml` - The main setup file for Travis
.. `travis/template/Dockerfile` - The main setup file for the openSUSE Docker container
.. `.dockerignore` - Files in your repo that should be ignored by Docker

. [Optional] By default, Travis will run over DC files matching the pattern `DC-\*-all`.
If none exist, it will use the pattern `DC-*` instead.
To set up any other set of DC files to check, add a file named `.travis-check-docs` to your repo.
In this file, list the names of all DC files to check, separated by newlines (`\n`) or spaces.

. Push the feature branch with:
+
----
git push --set-upstream origin feature/travis
----

. Wait and see for the results.
If you encounter an issue, contact link:https://github.com/tomschr/[@tomschr] or link:https://github.com/sknorr/[@sknorr].

. Merge your branch into `master`.


== Travis Draft Builds

We publish HTML builds of our public repositories on https://susedoc.github.io.
To build the documentation, we are using Travis CI which is already triggered for each commit.
Our Travis CI script downloads a configuration file from https://github.com/SUSEdoc/susedoc.github.io/blob/master/config.xml.
This file list all branches that are enabled for publishing.
If the commit that Travis is currently validating belongs to one of those branches, a build will be triggered.

After the build, Travis CI pushes the builds to the target repositories in the `susedoc` GitHub organization.
For that, each target repository has a SSH public key with write access that is used by Travis.
The SSH private key is stored in the corresponding source repository in an encrypted file.
Travis uses an internal private key to decrypt this SSH private key.

=== Configuring Travis CI

To create draft builds of branches in a repository, first enable Travis CI as described in the previous section.
Then follow this procedure:

. Install the Travis CLI as described in https://github.com/travis-ci/travis.rb#installation.
This can also be done on a machine you have SSH access to.

. If you followed the guide from Travis on an openSUSE machine, set the
following path after the installation:
+
----
export PATH="/usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.10/bin:$PATH"
----
+
(Adapt the path to your installed version of Ruby and the ``travis`` tool.)

. Create a new SSH key pair that can be used for deploying to GitHub pages.
Copy the encrypted private key to the documentation source code repository.

.. Create a new directory and in it key pair in the current working directory.
Do not set a password for the key file.
+
----
ssh-keygen -t rsa -b 4096 -C "doc-team@suse.com" -f id_rsa
----

.. Create a secret that will be used to encrypt the SSH private key:
+
----
echo $(openssl rand -base64 64 | tr -d '\n') > secret
----
+
Store the SSH key and also the secret in the link:https://gitlab.nue.suse.com/susedoc/doc-dotfiles/tree/master/ssh-travis[internal doc-dotfiles repository].

.. Encrypt the private key with the secret and copy the encrypted file to the documentation source repository.
+
----
openssl aes-256-cbc -md md5 -pass "file:./secret" -in ./id_rsa -out ./ssh_key.enc -a
cp ssh_key.enc /PATH/TO/XML/REPO/ssh_key.enc
cat secret
----
+
Copy and paste the string from the secret file.
You will need it for the next step.
+
The parameter `-md md5` is necessary to make sure that the same digest algorithm is used across various versions of OpenSSL (it probably also lowers security somewhat).
For more information, see https://stackoverflow.com/questions/34304570.

.. Create an environment variable named `ENCRYPTED_PRIVKEY_SECRET` that stores the secret.
Then encrypt this full string to be included in the `.travis.yml`:
+
----
travis encrypt -r SUSE/doc-repo ENCRYPTED_PRIVKEY_SECRET=INSERT_SECRET_STRING
----
+
Take the result and in the `.travis.yml` replace the string `ADD_ENCRYPTED_SECRET` with the result.
Do not copy the quotes from the result.
+
Some details why we are doing this: Travis CI needs to decrypt the SSH private key file on every run.
You can set environment variables in the Web UI of Travis CI for each repository.
For additional security, we will again encrypt the secret that Travis needs to decrypt the SSH key.
This is necessary because environment variables can leak over unwanted paths.
+
To achieve this encryption, Travis CI has a private and public key for each repository.
Travis CI keeps the private key and allows encrypting arbitrary data with the public key over its API.

. Create a repository in the SUSEDoc organization and add the SSH public key as a deployment key.

. Clone this repository locally, create a ``gh-pages`` branch in it and create an initial commit:
+
----
git clone git@github.com:SUSEdoc/doc-repo doc-repo-publish && doc-repo-publish
git checkout -b gh-pages
git commit --allow-empty -m"Initial Commit"
git push origin gh-pages
----

=== Setting Up a Git Branch to Publishing Builds

. Doc CI should already be set up.
If not, see <<travis-draft-builds>>.

. Configure builds and links to those builds using the instructions in https://github.com/SUSEdoc/susedoc.github.io/blob/master/README.md.

== Docker Image susedoc/ci

=== Building a Docker Image for dockerhub.com

. Within your local clone of this repository, go into the directory `build-docker-ci`.

. Run: `docker build .`
When the image is built, a SHA hash will be displayed.

. Try using the image for a couple of builds in `daps2docker`.
Install `daps2docker`, either bare from link:https://github.com/openSUSE/daps2docker[its Git repository] or as a package from the OBS Documentation:Tools repository.
Go to a documentation repository clone and run:
+
----
D2D_IMAGE=SHA_HASH daps2docker
----
+
If you are happy with the results, continue.
Otherwise, delete your container (`docker rmi -f SHA_HASH`) and rebuild with adjustments.

. Tag the image and upload it:
+
----
docker tag IMAGE_ID susedoc/ci:latest
docker tag IMAGE_ID susedoc/ci:openSUSE-15.1
docker push susedoc/ci:latest
docker push susedoc/ci:openSUSE-15.1
----
